apiVersion: v2
name: kubebb-core
annotations:
  core.kubebb.k8s.com.cn/displayname: "内核"
  core.kubebb.k8s.com.cn/restrict-tenants: "system-tenant"
  core.kubebb.k8s.com.cn/restricted-namespaces: "kubebb-system"
description: Kubebb Core provides core implementations on Component Lifecycle Management.Our design and development follows operator pattern which extends kubernetes APIs.
type: application
version: v0.1.27
appVersion: v0.1.6
icon: https://avatars.githubusercontent.com/u/85277200
keywords:
  - repository
  - helm
  - lifecycle-management
sources:
  - https://github.com/kubebb/core
maintainers:
  - name: bjwswang
    url: https://github.com/bjwswang
  - name: Abirdcfly
    url: https://github.com/Abirdcfly
  - name: 0xff-dev
    url: https://github.com/0xff-dev
