apiVersion: v2
name: kubebb-core
description: Kubebb Core provides core implementations on Component Lifecycle Management.Our design and development follows operator pattern which extends kubernetes APIs.
type: application
version: v0.1.9
appVersion: v0.1.3
icon: https://avatars.githubusercontent.com/u/85277200
keywords:
  - repository
  - helm
  - lifecycle-management
sources:
  - https://github.com/kubebb/core
maintainers:
  - name: bjwswang
    url: https://github.com/bjwswang
  - name: Abirdcfly
    url: https://github.com/Abirdcfly
  - name: 0xff-dev
    url: https://github.com/0xff-dev
